---
title: '190621'
author: "Lee"
date: '2019 6 21 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##### 1
```{r}
n <- 1000
df <- 3
ch.2.mean <- rep(NA, n)
ch.4.mean <- rep(NA, n)
ch.16.mean <- rep(NA, n)
ch.64.mean <- rep(NA, n)

for(i in 1:n) {
  ch.2.mean[i] <- mean(rchisq(2, df=df))
  ch.4.mean[i] <- mean(rchisq(4, df=df))
  ch.16.mean[i] <- mean(rchisq(16, df=df))
  ch.64.mean[i] <- mean(rchisq(64, df=df))
}

options(digits=4)
c(mean(ch.2.mean), sd(ch.2.mean))
c(mean(ch.4.mean), sd(ch.4.mean))
c(mean(ch.16.mean), sd(ch.16.mean))
c(mean(ch.64.mean), sd(ch.64.mean))

m <- df
s <- sqrt(2 * df)

par(mfrow=c(2,2), oma = c(0, 0, 2, 0))
hist(ch.2.mean, prob=T, main="표본 크기 : 2", 
     ylab="", xlab="", col="orange", border="red")
x1 <- seq(min(ch.2.mean), max(ch.2.mean), length=1000)
y1 <- dnorm(x=x1, mean=m, sd=s/sqrt(2))
lines(x1, y1, lty=2, lwd=2, col="blue")

hist(ch.4.mean, prob=T, main="표본 크기 : 4", 
     ylab="", xlab="", col="orange", border="red")
x2 <- seq(min(ch.4.mean), max(ch.4.mean), length=1000)
y2 <- dnorm(x=x2, mean=m, sd=s/sqrt(4))
lines(x2, y2, lty=2, lwd=2, col="blue")

hist(ch.16.mean, prob=T, main="표본 크기 : 16", 
     ylab="", xlab="", col="orange", border="red")
x3 <- seq(min(ch.16.mean), max(ch.16.mean), length=1000)
y3 <- dnorm(x=x3, mean=m, sd=s/sqrt(16))
lines(x3, y3, lty=2, lwd=2, col="blue")

hist(ch.64.mean, prob=T, main="표본 크기 : 64", 
     ylab="", xlab="", col="orange", border="red")
x4 <- seq(min(ch.64.mean), max(ch.64.mean), length=1000)
y4 <- dnorm(x=x4, mean=m, sd=s/sqrt(64))
lines(x4, y4, lty=2, lwd=2, col="blue")

mtext("Chi Square 표본평균 분포(df=3인 경우)", outer = TRUE, cex = 1.2)
```
<br><br>

##### 2
```{r}
n <- 1000
df <- 4
ch.2.mean <- rep(NA, n)
ch.4.mean <- rep(NA, n)
ch.8.mean <- rep(NA, n)
ch.16.mean <- rep(NA, n)

for(i in 1:n) {
  ch.2.mean[i] <- mean(rchisq(2, df=df))
  ch.4.mean[i] <- mean(rchisq(4, df=df))
  ch.8.mean[i] <- mean(rchisq(8, df=df))
  ch.16.mean[i] <- mean(rchisq(16, df=df))
}

options(digits=4)
c(mean(ch.2.mean), sd(ch.2.mean))
c(mean(ch.4.mean), sd(ch.4.mean))
c(mean(ch.8.mean), sd(ch.8.mean))
c(mean(ch.16.mean), sd(ch.16.mean))

m <- df
s <- sqrt(2 * df)

par(mfrow=c(2,2), oma = c(0, 0, 2, 0))
hist(ch.2.mean, prob=T, main="표본 크기 : 2", 
     ylab="", xlab="", col="orange", border="red")
x1 <- seq(min(ch.2.mean), max(ch.2.mean), length=1000)
y1 <- dnorm(x=x1, mean=m, sd=s/sqrt(2))
lines(x1, y1, lty=2, lwd=2, col="blue")

hist(ch.4.mean, prob=T, main="표본 크기 : 4", 
     ylab="", xlab="", col="orange", border="red")
x2 <- seq(min(ch.4.mean), max(ch.4.mean), length=1000)
y2 <- dnorm(x=x2, mean=m, sd=s/sqrt(4))
lines(x2, y2, lty=2, lwd=2, col="blue")

hist(ch.8.mean, prob=T, main="표본 크기 : 8", 
     ylab="", xlab="", col="orange", border="red")
x3 <- seq(min(ch.8.mean), max(ch.8.mean), length=1000)
y3 <- dnorm(x=x3, mean=m, sd=s/sqrt(8))
lines(x3, y3, lty=2, lwd=2, col="blue")

hist(ch.16.mean, prob=T, main="표본 크기 : 16", 
     ylab="", xlab="", col="orange", border="red")
x4 <- seq(min(ch.16.mean), max(ch.16.mean), length=1000)
y4 <- dnorm(x=x4, mean=m, sd=s/sqrt(16))
lines(x4, y4, lty=2, lwd=2, col="blue")

mtext("Chi Square 표본평균 분포(df=4인 경우)", outer = TRUE, cex = 1.2)
```
<br><br>

##### 3
```{r}
n <- 1000
df <- 5
ch.3.mean <- rep(NA, n)
ch.9.mean <- rep(NA, n)
ch.27.mean <- rep(NA, n)
ch.81.mean <- rep(NA, n)

for(i in 1:n) {
  ch.3.mean[i] <- mean(rchisq(3, df=df))
  ch.9.mean[i] <- mean(rchisq(9, df=df))
  ch.27.mean[i] <- mean(rchisq(27, df=df))
  ch.81.mean[i] <- mean(rchisq(81, df=df))
}

options(digits=4)
c(mean(ch.3.mean), sd(ch.3.mean))
c(mean(ch.9.mean), sd(ch.9.mean))
c(mean(ch.27.mean), sd(ch.27.mean))
c(mean(ch.81.mean), sd(ch.81.mean))

m <- df
s <- sqrt(2 * df)

par(mfrow=c(2,2), oma = c(0, 0, 2, 0))
hist(ch.3.mean, prob=T, main="표본 크기 : 3", 
     ylab="", xlab="", col="orange", border="red")
x1 <- seq(min(ch.3.mean), max(ch.3.mean), length=1000)
y1 <- dnorm(x=x1, mean=m, sd=s/sqrt(3))
lines(x1, y1, lty=2, lwd=2, col="blue")

hist(ch.9.mean, prob=T, main="표본 크기 : 9", 
     ylab="", xlab="", col="orange", border="red")
x2 <- seq(min(ch.9.mean), max(ch.9.mean), length=1000)
y2 <- dnorm(x=x2, mean=m, sd=s/sqrt(9))
lines(x2, y2, lty=2, lwd=2, col="blue")

hist(ch.27.mean, prob=T, main="표본 크기 : 27", 
     ylab="", xlab="", col="orange", border="red")
x3 <- seq(min(ch.27.mean), max(ch.27.mean), length=1000)
y3 <- dnorm(x=x3, mean=m, sd=s/sqrt(27))
lines(x3, y3, lty=2, lwd=2, col="blue")

hist(ch.81.mean, prob=T, main="표본 크기 : 81", 
     ylab="", xlab="", col="orange", border="red")
x4 <- seq(min(ch.81.mean), max(ch.81.mean), length=1000)
y4 <- dnorm(x=x4, mean=m, sd=s/sqrt(81))
lines(x4, y4, lty=2, lwd=2, col="blue")

mtext("Chi Square 표본평균 분포(df=5인 경우)", outer = TRUE, cex = 1.2)
```
<br><br>
